version: 2.1
workflows:
  ci-cd:
    jobs:
      - test
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

